"""Directional ANM construction and mechanical-perturbation scoring.

GNM/CTQW assigns one scalar state to each residue.  ANM instead assigns x/y/z
displacements, producing a ``3N x 3N`` Hessian.  This module uses that directional
operator when domain rotation and hinge mechanics matter, as in Myosin.
"""

from typing import Sequence

import numpy as np

from scipy.sparse import csr_matrix

from scipy.sparse.linalg import eigsh

from .structure import ResidueNode

def build_anm_hessian(
    residues: Sequence[ResidueNode],
    cutoff: float = 7.8,
) -> tuple[np.ndarray, np.ndarray]:
    """Build the standard C-alpha ANM Hessian and binary contact matrix.

    Every contact contributes the rank-one directional stiffness
    ``r_hat r_hat.T`` to the two diagonal blocks and its negative to the two
    cross-blocks.  The returned Hessian therefore acts on flattened xyz residue
    displacements.
    """

    if len(residues) < 2 or cutoff <= 0.0:
        raise ValueError("ANM requires at least two residues and a positive cutoff")
    coordinates = np.stack([residue.coordinate for residue in residues])
    displacements = coordinates[:, None, :] - coordinates[None, :, :]
    distances = np.linalg.norm(displacements, axis=-1)
    contacts = (distances <= cutoff) & (distances > 0.0)
    if np.any(contacts.sum(axis=1) == 0):
        raise ValueError("ANM contact graph contains isolated residues")

    # Each residue owns three consecutive coordinates: [x_i, y_i, z_i].
    size = 3 * len(residues)
    hessian = np.zeros((size, size), dtype=float)
    for first, second in zip(*np.nonzero(np.triu(contacts, 1))):
        direction = displacements[first, second] / distances[first, second]
        # Only displacement projected along the native contact direction stretches
        # this central-force spring; transverse motion has zero first-order cost.
        stiffness = np.outer(direction, direction)
        first_slice = slice(3 * first, 3 * first + 3)
        second_slice = slice(3 * second, 3 * second + 3)
        hessian[first_slice, first_slice] += stiffness
        hessian[second_slice, second_slice] += stiffness
        hessian[first_slice, second_slice] -= stiffness
        hessian[second_slice, first_slice] -= stiffness
    return hessian, contacts.astype(float)

def _low_anm_modes(
    hessian: np.ndarray,
    mode_count: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Return spectrally normalized, non-rigid low-frequency ANM modes.

    Dense diagonalization is cheaper for small systems.  Larger Hessians use sparse
    shift-invert eigensolving near zero, with a fixed start vector for reproducible
    results.  Extra requested eigenpairs leave room for rigid zero modes.
    """

    if mode_count < 1:
        raise ValueError("mode_count must be positive")
    size = len(hessian)
    if size <= mode_count + 13:
        eigenvalues, eigenvectors = np.linalg.eigh(hessian)
        eigenvalues /= max(float(eigenvalues[-1]), 1e-12)
    else:
        sparse = csr_matrix(hessian)
        start_vector = np.linspace(1.0, 2.0, size)
        spectral_scale = float(
            eigsh(
                sparse,
                k=1,
                which="LA",
                return_eigenvectors=False,
                v0=start_vector,
            )[0]
        )
        # Six rigid modes are expected, but requesting twelve spare modes also
        # tolerates a small number of cutoff-dependent floppy modes.
        requested = min(size - 1, mode_count + 12)
        eigenvalues, eigenvectors = eigsh(
            sparse / max(spectral_scale, 1e-12),
            k=requested,
            sigma=1e-8,
            which="LM",
            v0=start_vector,
        )
        order = np.argsort(eigenvalues)
        eigenvalues, eigenvectors = eigenvalues[order], eigenvectors[:, order]
    tolerance = max(float(np.max(np.abs(eigenvalues))) * 1e-9, 1e-10)
    keep = eigenvalues > tolerance
    return eigenvalues[keep][:mode_count], eigenvectors[:, keep][:, :mode_count]

def anm_fluctuation_connectivity(
    residues: Sequence[ResidueNode],
    cutoff: float = 10.0,
    mode_count: int = 100,
    batch_size: int = 256,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Measure global fluctuation response to local native-spring stiffening.

    Returns:
        ``connectivity``: ``N x N`` perturbation-response matrix.  Row ``i``
        aggregates perturbations of springs incident on residue ``i``; column ``j``
        is the normalized fluctuation response observed at residue ``j``.
        ``hinge_scores``: number of above-reference responses generated by each row.
        ``adjacency``: binary ANM contact graph used to define mechanical shells.
    """

    hessian, adjacency = build_anm_hessian(residues, cutoff=cutoff)
    eigenvalues, modes = _low_anm_modes(hessian, mode_count)
    if not len(eigenvalues):
        raise ValueError("ANM has no retained non-rigid modes")
    node_count = len(adjacency)
    coordinates = np.stack([residue.coordinate for residue in residues])
    mode_blocks = modes.reshape(node_count, 3, -1)
    # Baseline modal variance at residue j is sum_k |u_jk|^2 / lambda_k.
    fluctuations = np.sum(mode_blocks**2 / eigenvalues, axis=(1, 2))
    fluctuations = np.maximum(fluctuations, 1e-15)
    edges = np.argwhere(np.triu(adjacency, 1) > 0.0)
    connectivity = np.zeros_like(adjacency)

    # Process contact perturbations in batches to avoid materializing an
    # (edge_count x 3N x mode_count) tensor for large motor domains.
    for start in range(0, len(edges), batch_size):
        edge_batch = edges[start : start + batch_size]
        displacements = coordinates[edge_batch[:, 0]] - coordinates[edge_batch[:, 1]]
        directions = displacements / np.linalg.norm(displacements, axis=1)[:, None]
        strains = np.einsum(
            "ei,eim->em",
            directions,
            mode_blocks[edge_batch[:, 0]] - mode_blocks[edge_batch[:, 1]],
        )
        # Project each spring direction into modal space, apply 1/lambda Green
        # weighting, then reconstruct the displacement field over all residues.
        green_edges = np.einsum(
            "dm,em->ed",
            modes,
            strains / eigenvalues,
            optimize=True,
        ).reshape(len(edge_batch), node_count, 3)
        # Normalize by native fluctuation amplitude so flexible residues do not win
        # solely because their unperturbed motion is already large.
        response = np.sum(green_edges**2, axis=2) / fluctuations[None, :]
        np.add.at(connectivity, edge_batch[:, 0], response)
        np.add.at(connectivity, edge_batch[:, 1], response)

    # A narrow geometric shell provides a structure-derived reference scale.  Hinge
    # score counts how broadly a local perturbation exceeds that typical response.
    distances = np.linalg.norm(coordinates[:, None] - coordinates[None, :], axis=2)
    shell = (distances >= 9.5) & (distances <= 10.5)
    if not np.any(shell):
        raise ValueError("ANM has no residue pairs in the 10-Angstrom reference shell")
    threshold = float(connectivity.T[shell].mean())
    hinge_scores = np.count_nonzero(connectivity > threshold, axis=1).astype(float)
    return connectivity, hinge_scores, adjacency
